package com.example.project.controller;

import com.example.project.repository.UserRepository;
import com.example.project.dataobject.User;
import com.example.project.util.Constants;
import com.example.project.util.userEnumType;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.web.bind.annotation.*;

@Controller    // This means that this class is a Controller
public class HomeController {
	@Autowired // This means to get the bean called userRepository
			   // Which is auto-generated by Spring, we will use it to handle the data
	private UserRepository userRepository;


	@GetMapping(path="/")
	public String hello(Model model) {
		model.addAttribute("message", "world");
		return "home";
	}

	@GetMapping(path="/login")
	public String loginPage(Model model) {
		return "login";
	}

	@PostMapping(path="/login")
	public String login(Model model, @RequestParam String password, @RequestParam String email) {

		User result = userRepository.findByEmail(email);
		if (password.equals(result.getPassword())) {
			model.addAttribute("user", result);
			model.addAttribute("message", Constants.LOGINSUCCESS);
		} else {
			model.addAttribute("message", Constants.LOGINFAILED);
		}
		return "home";
	}


	@GetMapping(path="/signup")
	public String signupPage(Model model) {
		model.addAttribute("user", new User());
		return "signup";
	}


	@PostMapping(path="/signup")
	public String signup(Model model, @RequestParam String username
			,@RequestParam String password, @RequestParam String email) {
		User user = new User();
		user.setEmail(email);
		user.setUsername(username);
		user.setEmail(password);
		user.setType(userEnumType.MEMEBER.getValue());
		userRepository.save(user);
		model.addAttribute("message", "Sign Up success");
		return "home";
	}

	@PostMapping(path="/add") // Map ONLY POST Requests
	public @ResponseBody String addNewUser (@RequestParam String username
			,@RequestParam String password, @RequestParam String email) {
		// @ResponseBody means the returned String is the response, not a view name
		// @RequestParam means it is a parameter from the GET or POST request

		User n = new User();
		n.setUsername(username);
		n.setEmail(email);
		n.setPassword(password);
		userRepository.save(n);
		return "Saved";
	}

	@GetMapping(path="/all")
	public @ResponseBody Iterable<User> getAllUsers() {
		// This returns a JSON or XML with the users
		return userRepository.findAll();
	}
}
